### PR TITLE
Simplify Package Time-Based Group Detection

### LINKED ISSUE #51: [Group Package] 1 group include 3 billable metrics => push event => not generate charge
**Describe the bug**
Plan has 1 group (4 articles & 5GB & 5 minutes) => push event => not charge

**Pre-condition**
Plan A has 1 group including billable metrics: 4 articles & 5GB & 5 minutes - 4$

**To Reproduce**
1. Assign plan A to customer X
2. Push event in the 1st time (by sending "Add event" API in Postman) with:
      "code": "4_articles",
      "properties": {"storage": 2} 
3. Go to Invoices tab of customer X to check generating a new invoice
4. Not generate any new invoice

**Expected behavior**
Generating a new invoice with charge = 4$

**Screenshots**
https://www.loom.com/share/134a77bb43114ec4b52b3c435b77a268?sid=2b4bbf97-ad5a-4a7b-ba12-7ed9387e8e62

**Notes**
When push event with this information => also not generate a new charge
     

>  "code": "5gb",

     

>  "properties": {"5gb": 2}

### PR DESCRIPTION
**Pull request by TronTram**
## What
- Change `Charge Group Type` determination logic
   + `packages_group`: all charges within the group are package_group charge.
   + `package_timebased_group`: A charge group contains one timebased charge.
   
## Why
- To fix #51 

## Self test
- Subscribe to a plan has 3 billable metrics
image

- Create an invoice when push event:
image

### CODE REVIEW

File: app/services/utils/charge_group_type_determiner_service.rb [hunk 1]
```diff
@@ -16,37 +16,18 @@ def call
     attr_reader :charge_group
 
     def charge_group_type
-      return Constants::CHARGE_GROUP_TYPES[:PACKAGES_GROUP] if is_packages_group?
-      return Constants::CHARGE_GROUP_TYPES[:PACKAGE_TIMEBASED_GROUP] if is_package_timebased_group?
+      return Constants::CHARGE_GROUP_TYPES[:PACKAGES_GROUP] if all_charges_are_package_group?
+      return Constants::CHARGE_GROUP_TYPES[:PACKAGE_TIMEBASED_GROUP] if has_one_timebased_charge?
```
Comment (tnlong311) [inline app/services/utils/charge_group_type_determiner_service.rb:20]: Should the condition be `has_one_timebased_charge? && has_at_least_one_package_group?`

Comment (TronTram) [reply app/services/utils/charge_group_type_determiner_service.rb:20]: nice! let's me add

**Review by tnlong311 — APPROVED** [review]
